name: Deploy shared and staging environments

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write

jobs:
  apply-shared:
    name: Apply shared environment
    runs-on: ubuntu-24.04-arm
    environment: shared
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true
    outputs:
      registry-name: ${{ steps.terraform-outputs.outputs.registry-name }}
      resource-group-name: ${{ steps.terraform-outputs.outputs.resource-group-name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform apply
        uses: ThorstenSauter/terraform-actions/apply@v1
        with:
          terraform-version: ${{ vars.TERRAFORM_VERSION }}
          infra-directory: ${{ vars.TF_WORKING_DIRECTORY }}
          resource-group: ${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }}
          storage-account: ${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }}
          container: ${{ vars.TF_BACKEND_STATE_CONTAINER_NAME }}
          state-file: ${{ vars.TF_BACKEND_STATE_FILE_NAME }}
      - name: Get Terraform outputs
        id: terraform-outputs
        working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
        run: |
          echo "registry-name=$(terraform output -raw registry_name)" >> "$GITHUB_OUTPUT"
          echo "resource-group-name=$(terraform output -raw resource_group_name)" >> "$GITHUB_OUTPUT"

  build:
    name: Build container image
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      image-name: ${{ steps.image-details.outputs.image-name }}
    needs:
      - apply-shared
    env:
      PROJECT_PATH: 'src/TShort.Api/TShort.Api.csproj'
      REGISTRY_NAME: ${{ needs.apply-shared.outputs.registry-name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          source-url: ${{ vars.NUGET_FEED_URI }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_GITHUB_PACKAGES_TOKEN }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.REGISTRY_NAME }}
      - name: Build image
        run: |
          dotnet publish \
          -p:PublishProfile=DefaultContainer \
          -p:ContainerRepository=${{ vars.API_IMAGE_NAME }} \
          -p:ContainerRegistry=${{ env.REGISTRY_NAME }}.azurecr.io \
          -p:ContainerImageTag=${{ github.sha }} \
          ${{ env.PROJECT_PATH }}
      - name: Output image details
        id: image-details
        run: |
          name=${{ env.REGISTRY_NAME }}.azurecr.io/${{ vars.API_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker pull $name
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' $name | awk -F'@' '{print $2}')
          echo "image-name=$name" >> "$GITHUB_OUTPUT"
          echo "image-digest=$digest" >> "$GITHUB_OUTPUT"
      - name: Generate container image attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ vars.API_IMAGE_NAME }}
          subject-digest: ${{ steps.image-details.outputs.image-digest }}
          push-to-registry: true

  migration-bundle:
    name: Build and apply database migration bundle
    runs-on: ubuntu-latest
    environment: staging
    needs:
      - apply-shared
      - build
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      MIGRATION_BUNDLE_NAME: 'apply-migrations'
      OUTPUT_DIR: 'publish'
      PROJECT_PATH: 'src/TShort.Api/TShort.Api.csproj'
      TF_VAR_api_container_image_name: ${{ needs.build.outputs.image-name }}
      TF_VAR_container_registry_resource_group: ${{ needs.apply-shared.outputs.resource-group-name }}
      TF_VAR_entra_id_client_secret: ${{ secrets.ENTRA_ID_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform init
        uses: ThorstenSauter/terraform-actions/init@v1
        with:
          terraform-version: ${{ vars.TERRAFORM_VERSION }}
          infra-directory: ${{ vars.TF_WORKING_DIRECTORY }}
          resource-group: ${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }}
          storage-account: ${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }}
          container: ${{ vars.TF_BACKEND_STATE_CONTAINER_NAME }}
          state-file: ${{ vars.TF_BACKEND_STATE_FILE_NAME }}
      - name: Terraform apply refresh only
        working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
        run: terraform apply -refresh-only -auto-approve -input=false
      - name: Retrieve database outputs
        id: database-output-retrieval
        working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
        run: |
          server=$(terraform output -raw sql_server_fqdn)
          echo "server=$server" >> "$GITHUB_OUTPUT"
          database=$(terraform output -raw sql_server_database)
          echo "database=$database" >> "$GITHUB_OUTPUT"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          source-url: ${{ vars.NUGET_FEED_URI }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_GITHUB_PACKAGES_TOKEN }}
      - name: Install dotnet-ef tool
        run: dotnet tool install -g dotnet-ef
      - name: Generate EF core migrations bundle
        run: dotnet-ef migrations bundle --project ${{ env.PROJECT_PATH }} --output ${{ env.MIGRATION_BUNDLE_NAME }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
      - name: Run migration bundle
        run: ./${{ env.MIGRATION_BUNDLE_NAME }} --connection "${{ env.CONNECTION_STRING }}"
        env:
          CONNECTION_STRING: >-
            Server=tcp:${{ steps.database-output-retrieval.outputs.server }},1433;
            Authentication=Active Directory Default;
            Database=${{ steps.database-output-retrieval.outputs.database }};
            User ID=${{ vars.AZURE_CLIENT_ID }};
            Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

  apply-staging:
    name: Apply staging environment
    runs-on: ubuntu-24.04-arm
    environment: staging
    needs:
      - apply-shared
      - build
      - migration-bundle
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_api_container_image_name: ${{ needs.build.outputs.image-name }}
      TF_VAR_container_registry_resource_group: ${{ needs.apply-shared.outputs.resource-group-name }}
      TF_VAR_entra_id_client_secret: ${{ secrets.ENTRA_ID_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform apply
        uses: ThorstenSauter/terraform-actions/apply@v1
        with:
          terraform-version: ${{ vars.TERRAFORM_VERSION }}
          infra-directory: ${{ vars.TF_WORKING_DIRECTORY }}
          resource-group: ${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }}
          storage-account: ${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }}
          container: ${{ vars.TF_BACKEND_STATE_CONTAINER_NAME }}
          state-file: ${{ vars.TF_BACKEND_STATE_FILE_NAME }}

  deploy-web:
    name: Deploy to staging Azure Static Web App
    needs:
      - apply-shared
      - apply-staging
      - build
    runs-on: ubuntu-latest
    environment: staging
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      OUTPUT_DIR: 'publish'
      PROJECT_PATH: 'src/TShort.Web/TShort.Web.csproj'
      TF_VAR_api_container_image_name: ${{ needs.build.outputs.image-name }}
      TF_VAR_container_registry_resource_group: ${{ needs.apply-shared.outputs.resource-group-name }}
      TF_VAR_entra_id_client_secret: ${{ secrets.ENTRA_ID_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform init
        uses: ThorstenSauter/terraform-actions/init@v1
        with:
          terraform-version: ${{ vars.TERRAFORM_VERSION }}
          infra-directory: ${{ vars.TF_WORKING_DIRECTORY }}
          resource-group: ${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }}
          storage-account: ${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }}
          container: ${{ vars.TF_BACKEND_STATE_CONTAINER_NAME }}
          state-file: ${{ vars.TF_BACKEND_STATE_FILE_NAME }}
      - name: Terraform apply refresh only
        working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
        run: terraform apply -refresh-only -auto-approve -input=false
      - name: Retrieve deployment token
        id: token-retrieval
        working-directory: ${{ vars.TF_WORKING_DIRECTORY }}
        run: |
          token=$(terraform output -raw deployment_token)
          echo "::add-mask::$token"
          echo "deployment-token=$token" >> "$GITHUB_OUTPUT"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          source-url: ${{ vars.NUGET_FEED_URI }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_GITHUB_PACKAGES_TOKEN }}
      - name: Install wasm-tools
        run: dotnet workload install wasm-tools
      - name: Publish
        run: |
          dotnet publish \
          -p:SourceRevisionId=${{ github.sha }} \
          -o ${{ env.OUTPUT_DIR }} \
          ${{ env.PROJECT_PATH }}
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.token-retrieval.outputs.deployment-token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '${{ env.OUTPUT_DIR }}/wwwroot'
          skip_api_build: true
          skip_app_build: true
          output_location: ''
